# Generated by Django 5.1.7 on 2025-04-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "pub_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[("SVM", "SVM模型"), ("LSTM", "LSTM模型")],
                        max_length=10,
                        verbose_name="模型类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "新闻",
                "verbose_name_plural": "新闻",
                "ordering": ["-pub_date"],
            },
        ),
    ]
